language: python
python: 3.5
install:
  - pip install tox
  - pip install coverage
script:
  - tox
env:
  - TOXENV=py27-django
  - TOXENV=py34-django
  - TOXENV=py35-django
branches:
  only:
    - stable/2.9.x
